### ISSUE TITLE
Public directory

### ISSUE THREAD

**Issue by JikkuJose** [alicoding/react-webpack-babel#75]
We shouldn't be committing the changes to public directory right? But I see no reference of it in a rather comprehensive .gitignore. Was this on purpose?

**Comment by alicoding** [comment]
It was not on purpose, but I left it up to the people who forked it to modify the way they need it to be. I can ignore that if you think it's better?

**Comment by JikkuJose** [comment]
Yes, I think a lot of cruft will go away if you ignore it.

**Comment by alicoding** [comment]
Do you mind send a small PR as to what you think should be ignored?

**Comment by JikkuJose** [comment]
Done, have sent a pull request.

**Comment by alicoding** [comment]
Thank you once again!

**Comment by hugotox** [comment]
if public is not included where are we supposed to put static files?

**Comment by alicoding** [comment]
@hugotox when you build you still getting that but we are just not commiting that to the repo
